### ISSUE TITLE
Typo on `Organization`, but you can ignore it

### ISSUE THREAD

**Issue by riflowth** [waranatcpe/mock-data#1]
Did you mean `organization`?

https://github.com/waranatcpe/mock-data/blob/main/src/index.ts#L24
https://github.com/waranatcpe/mock-data/blob/main/src/index.ts#L35
https://github.com/waranatcpe/mock-data/blob/main/README.md

**Comment by waranatcpe** [comment]
Oh, thx

**Comment by riflowth** [comment]
@waranatcpe, you're too fast 💯
